web:
  build: .
  volumes:
    - "./app:/src/app"
  ports:
    - "6000:3000"
    - "35729:35729"
  links:
    - "db:redis"

nginx:
  restart: always
  build: ./nginx/
  ports:
    - "5000:80"
  volumes:
    - /www/public
  volumes_from:
    - web
  links:
    - web:web

db:
  image: redis
